# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
