# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Party name'),
        ),
    ]
